version: 0.2

run-as: root


phases:
   pre_build:
     commands:
       - echo "mongodb-url-aarsh=$mongodb-url-aarsh" > .env

   build:
     commands:
        - echo "build application"
       

artifacts:
  files:
    - echo "Upload artifact to bucket for deploy"
    - '**/*'
